# .github/workflows/norminette.yml
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
name: norminette

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v2
      with:
        flags: '.'
